### ISSUE TITLE
Firefox `--class` argument

### ISSUE THREAD

**Issue by james-smith-za** [amirkarimi/browser-hub#1]
https://github.com/amirkarimi/browser-hub/blob/575ff40c736cf80dd98f4d2932538d53a89ec5fb/README.md?plain=1#L142

In the `open_cmd` in the example Firefox config, you've got a `--class` argument, which I can't find documented anywhere in the Firefox cli options.

Can you point me in the direction of what it does?

**Comment by amirkarimi** [comment]
I guess I found it in some forums but here is some reference from Arch wiki: https://wiki.archlinux.org/title/firefox#Window_manager_rules
